services:
  - type: web
    name: pmas-backend
    env: python
    plan: free
    rootDir: .
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DISABLE_POETRY
        value: "true"
